# Generated by Django 4.0.4 on 2022-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Достижение')),
            ],
        ),
    ]
